image: leapcode/ruby

# This is for caching the gems not only between the stages, but also persistent
# on the gitlab-runner so we don't need to install from scratch on every pipeline
cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - tests/platform-ci/vendor/

before_script:
  - cd tests/platform-ci

stages:
  - setup
  - syntax
  - build

setup:
  stage: setup
  script:
    - ./setup.sh

lint:
  stage: syntax
  script:
    - /usr/local/bin/bundle exec rake lint

syntax:
  stage: syntax
  script:
    - /usr/local/bin/bundle exec rake syntax

validate:
  stage: syntax
  script:
    - /usr/local/bin/bundle exec rake validate

templates:
  stage: syntax
  script:
    - /usr/local/bin/bundle exec rake templates

catalog:
  stage: syntax
  script:
    - /usr/local/bin/bundle exec rake catalog

#rspec:
#  stage: rspec
#  script:
#    - /usr/local/bin/bundle exec rake spec

build:
  stage: build
  script:
    - /usr/bin/unbuffer ./ci-build.sh | /usr/bin/ts -s
