before_script:
  - ruby -v
  - bundle install --path vendor/bundle --jobs $(nproc)  "${FLAGS[@]}"
  - git submodule update --init

stages:
  - syntax
# - rspec
  - build

# doesn't work in docker atm
# image: ruby:2.1

lint:
  stage: syntax
  script:
    - bundle exec rake lint

syntax:
  stage: syntax
  script:
    - bundle exec rake syntax

validate:
  stage: syntax
  script:
    - bundle exec rake validate

templates:
  stage: syntax
  script:
    - bundle exec rake templates

catalog:
  stage: syntax
  script:
    - bundle exec rake catalog

#rspec:
#  stage: rspec
#  script:
#    - bundle exec rake spec

build:
  stage: build
  script:
    - echo $CI_BUILD_REF_NAME
    - ssh testbot@greyhound.leap.se -p 4422 "/usr/local/bin/platform_test/buildscripts/build-on-greyhound.sh $CI_BUILD_REF_NAME -x"
