before_script:
  - echo 'Running global before_script'
  - bundle install --path vendor/bundle --jobs $(nproc)  "${FLAGS[@]}"

stages:
  - syntax
  - build

# doesn't work in docker atm
# image: ruby:2.1

lint:
  stage: syntax
  script:
    - bundle exec rake lint
  allow_failure: true

syntax:
  stage: syntax
  script:
    - bundle exec rake syntax
  allow_failure: true

validate:
  stage: syntax
  script:
    - bundle exec rake validate
  allow_failure: true

templates:
  stage: syntax
  script:
    - bundle exec rake templates

catalog:
  stage: syntax
  script:
    - bundle exec rake catalog

build:
  stage: build
  script:
    - ./bin/ci-build.sh
