before_script:
  - echo 'Running global before_script'
  - bundle install --path vendor/bundle --jobs $(nproc)  "${FLAGS[@]}"

stages:
  - syntax
# - rspec
  - build

# doesn't work in docker atm
# image: ruby:2.1

lint:
  stage: syntax
  script:
    - bundle exec rake lint

syntax:
  stage: syntax
  script:
    - bundle exec rake syntax

validate:
  stage: syntax
  script:
    - bundle exec rake validate

templates:
  stage: syntax
  script:
    - bundle exec rake templates

catalog:
  stage: syntax
  script:
    - bundle exec rake catalog

#rspec:
#  stage: rspec
#  script:
#    - bundle exec rake spec

build:
  stage: build
  before_script:
    - env
  script:
    # use simple_deploy to speed up local development
    #- leap-platform-test simple_deploy
    - leap-platform-test -v reset_deploy
    - leap-platform-test -v test
    - leap info
    - leap local stop
